server:
    port: 5299
    servlet:
        context-path: /springboot_emp
spring:
    datasource:
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/novel
        driver-class-name: com.mysql.jdbc.Driver
        username: root
    mvc:
        view:
            prefix: /
            suffix: .jsp
    profiles:
      active: product
    http:
        encoding:
            force-response: true
            charset: UTF-8
            force: true
            force-request: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 500MB
    jackson:
        date-format: 'yyyy-MM-dd'
        time-zone: GMT+8
    redis:
        host: 192.168.11.64
        database: 0
        port: 5299

    data:
        elasticsearch:
            cluster-nodes: 192.168.11.66:9300
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.baizhi.entity
logging:
    level:
      root: error